
[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij"]

[window]
decorations = "None"
startup_mode = "Maximized"
opacity = 0.9
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

